masters/masters/urls.py
from django.contrib import admin
from django.urls import path, include
from masters import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
    path('student/', include('student.urls')),
    path('professor/', include('professor.urls')),
    path('staff/', include('staff.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masters/staff/urls.py
from django.urls import path
from staff import views, professorView, studentView

app_name = 'staff'

urlpatterns = [
    # PROFESSOR CRUD
    path('add/professor/', professorView.addProfessor, name='add_professor'),
    path('professors/', professorView.addProfessor, name='professor_list'),
    path('professor/<int:id>/edit/', professorView.professorEdit, name='professor_edit'),
    
    # STUDENT CRUD
    path('student/<int:id>/edit/', studentView.studentEdit, name='student_edit'),
    path('add/student/', studentView.addStudent, name='add_student'),
    path('students/', studentView.addStudent, name='student_list'),
    
    # SYSTEM CRUD
    path('add/group/', views.addGroup, name='add_group'),
    path('group/admin/<int:id>', views.setGroupAdmin, name='set_group_admin'),
    path('add/orientation/', views.addOrientation, name='add_orientation'),
    path('group/<int:id>/edit/', views.editGroup, name='edit_group'),
    path('group/<int:id>/delete/', views.error, name='delete_group'),
    path('orientation/<int:id>/edit/', views.editOrientation, name='edit_orientation'),
    path('orientation/<int:id>/delete/', views.deleteOrientation, name='delete_orientation'),
    
    # GET
    path('groups/', views.groups, name='groups'),
    path('group/<int:id>/orientations/', views.groupOrientationList, name='group_orientation_list'),
    path('group/<int:id>/professors/', views.groups, name='group_professor_list'),
    path('group/<int:id>/students/', views.groups, name='group_student_list'),
    path('orientation/<int:id>/students/', views.groups, name='orientation_student_list'),
    path('error/', views.error, name='error'),
    path('<str:username>/', views.dashboard, name='dashboard'),
]

masters/staff/forms.py
from django import forms
from professor.models import Professor, ProfessorFields
from phonenumber_field.formfields import PhoneNumberField
from system.models import Group, Orientation, User
from student.models import Student, StudentFields
from django.core.exceptions import ValidationError

# from ckeditor.fields import RichTextFormField

class UserForm(forms.ModelForm):
    class Meta:
        model  = User
        fields = ['first_name', 'last_name', 'username', 'n_code', 'email', 'phone', 'gender']

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if first_name.isdigit():
            raise forms.ValidationError('نوع ورودی نامعتبر')
        return first_name


    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if last_name.isdigit():
            raise forms.ValidationError('نوع ورودی نامعتبر')
        return last_name


    def clean_username(self):
        username = self.cleaned_data['username']
        print(username)
        if len(username) != 10:
            raise forms.ValidationError('نام کاربری (شماره دانشجویی و کد پرسنلی) ۱۰ رقم است!')
        if not username.isdigit():
            raise forms.ValidationError('نام کاربری (شماره دانشجویی و کد پرسنلی) عدد است!')
        return username

    def clean_n_code(self):
        n_code = self.cleaned_data['n_code']
        print(n_code)
        if len(n_code) != 10:
            raise forms.ValidationError('کدملی ۱۰ رقم است!')
        if not n_code.isdigit():
            raise forms.ValidationError('کدملی عدد است!')
        return n_code




    # def clean_phone(self):
    #     phone = self.cleaned_data['phone']
    #     if len(phone) != 10:
    #         raise forms.ValidationError('کدملی ۱۰ رقم است!')
    #     if not phone.isdigit():
    #         raise forms.ValidationError('کدملی عدد است!')
    #     return phone



# class PFForm(forms.ModelForm):
#     class Meta:
#         model  = ProfessorFields
#         fields = ['grade', 'last_university']



# class StudentForm(forms.ModelForm):


#     class Meta:
#         model  = Student
#         fields = ['first_name', 'last_name', 'username', 'n_code', 'email', 'phone', 'gender']
#         # fields = "__all__"

#     def clean_username(self):
#         username = self.cleaned_data.get('username')
#         if len(username) != 10:
#             raise forms.ValidationError('شماره دانشجویی ۱۰ رقم است!')
#         if not username.isdigit():
#             raise forms.ValidationError('شماره دانشجویی عدد است!')
#         return username

#     def clean_n_code(self):
#         n_code = self.cleaned_data.get('n_code')
#         if len(n_code) != 10:
#             raise forms.ValidationError('کدملی ۱۰ رقم است!')
#         if not n_code.isdigit():
#             raise forms.ValidationError('کدملی عدد است!')
#         return n_code


# # class SFForm(forms.ModelForm):
# #     class Meta:
# #         model  = ProfessorFields
#         # fields = ['grade', 'last_university']


class GroupForm(forms.ModelForm):
    class Meta:
        model  = Group
        fields = ["title"]

    def clean_title(self):
        title = self.cleaned_data['title']
        if not title:
            raise forms.ValidationError('عنوان گروه نمی‌تواند خالی باشد')
        if title.isdigit():
            raise forms.ValidationError('عنوان گروه شامل عدد نمی‌شود!')
        return title

#     # def clean_title(self):
#     #     title = self.cleaned_data['title']
#     #     if len(title) < 10:
#     #         raise forms.ValidationError('سلام علیکم عذرا خانوم!')
#     #     return title

class OrientationForm(forms.ModelForm):
    class Meta:
        model  = Orientation
        fields = ["title"]


# # class StudentForm(forms.ModelForm):

# #     # GENDER = (
# #     #     ('female', 'مونث'),
# #     #     ('male', 'مذکر'),
# #     #     ('none', 'سایر'),
# #     # )

# #     # first_name = forms.CharField(label='نام', max_length=30, required=True)
# #     # last_name  = forms.CharField(label='نام خانوادگی', max_length=30, required=True)
# #     # username   = forms.CharField(label='نام کاربری(کد دانشجویی، کد پرسنلی)', max_length=30, required=False)
# #     # n_code     = forms.CharField(label='کد ملی', required=True)
# #     # email      = forms.EmailField(label='ایمیل', required=True)
# #     # phone      = PhoneNumberField(required=True, required=True)
# #     # college    = forms.CharField(max_length=20, required=True)
# #     # item_type  = forms.CharField(max_length=10, required=True)
# #     # gender     = forms.ChoiceField(choices=GENDER, required=True)


# #     class Meta:
# #         model  = Student
# #         fields = ['first_name', 'last_name', 'username', 'n_code', 'email', 'phone', 'college', 'item_type', 'gender']
# #         # fields = "__all__"

# #     def clean_username(self):
# #         username = self.cleaned_data.get('username')
# #         if len(username) != 10:
# #             raise forms.ValidationError('شماره دانشجویی ۱۰ رقم است!')
# #         if not username.isdigit():
# #             raise forms.ValidationError('شماره دانشجویی عدد است!')
# #         return username

# #     def clean_n_code(self):
# #         n_code = self.cleaned_data.get('n_code')
# #         if len(n_code) != 10:
# #             raise forms.ValidationError('کدملی ۱۰ رقم است!')
# #         if not n_code.isdigit():
# #             raise forms.ValidationError('کدملی عدد است!')
# #         return n_code


# # class SFForm(forms.Form):
# #     class Meta:
# #         model  = StudentFields
# #         fields = ['is_daily', 'last_university']


# # class UserUpdateForm(UserForm):
# #     about_me = RichTextFormField(max_length=700)

# #     def __init__(self, *args, **kwargs):
# #         super(UserUpdateForm, self).__init__(*args, **kwargs)
# #         self.fields['email'].disabled = True
# #         # self.fields.pop('password')

# #     class Meta(UserForm.Meta):
# #         fields = ['about_me', 'first_name', 'last_name', 'username', 'email', 'gender']

# # class AvatarUpdateForm(forms.ModelForm):
# #     class Meta:
# #         model  = AvatarModel
# #         fields = ['avatar']


# # class ResetPasswordForm(forms.Form):
# #     password       = forms.CharField(widget=forms.PasswordInput())
# #     password_check = forms.CharField(widget=forms.PasswordInput())


# #     def clean(self):
# #         cleaned_data   = super().clean()
# #         password       = cleaned_data.get('password')
# #         password_check = cleaned_data.get('password_check')

# #         if len(password) < 8:
# #             raise forms.ValidationError('حداقل ۸ کاراکتر لازمه...')


# #         if password != password_check:
# #             raise forms.ValidationError('گذرواژه ها با هم همخوان نیست...')


# #         # check for digit
# #         if not any(char.isdigit() for char in password):
# #             raise forms.ValidationError(('حداقل ۱ عدد باید داشته باشه...'))

# #         # check for letter
# #         if not any(char.isalpha() for char in password):
# #             raise forms.ValidationError(('...حداقل ۱ حرف باید داشته باشه'))

# #         return password

        


# # class GetEmailForm(forms.Form):
# #     email = forms.EmailField(required=True)

masters/staff/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.conf import settings
# from django.views import View

from staff.forms import UserForm, GroupForm, OrientationForm
from system.models import Group, User, Orientation, Adminstrator
from professor.models import Professor, ProfessorFields
from student.models import Student, StudentFields
from masters.settings import EMAIL_HOST_USER
from django.core.mail import send_mail


SUBJECT = 'تحصیلات تکمیلی دانشگاه بوعلی سینا'



@login_required
def addGroup(request):
    if request.user.item_type != User.Types.STAFF:
        messages.error(request, 'دسترسی ندارید!')
        return redirect('system:logout')

    if request.method == "POST":
        form = GroupForm(request.POST)        
        if form.is_valid():
            instance = form.save(commit=False)
            user     = request.user 
            college  = ''
            if user.item_type == User.Types.STAFF:
                college = user.stafffields.college
            else:
                return redirect('system:logout')
            instance.college = college
            instance.save()
            messages.success(request, 'گروه اضافه شد')        
            return redirect('staff:dashboard', username=user.username)
    else:
        form = GroupForm()
    
    return render(request, 'staff/system/addGroup.html', {'form': form})



@login_required
def editGroup(request, id):

    return render(request, 'staff/error.html', context=None)



@login_required
def editOrientation(request, id):

    return render(request, 'staff/error.html', context=None)


@login_required
def deleteOrientation(request, id):

    return render(request, 'staff/error.html', context=None)



@login_required
def setGroupAdmin(request, id):
    if request.user.item_type != User.Types.STAFF:
        messages.error(request, 'Access denied!')
        return redirect('system:logout')
    try:
        group = Group.objects.get(id=id)
        pfs   = ProfessorFields.objects.filter(group=group)
    except ObjectDoesNotExist:
        messages.error(request, 'گروه مورد نظر وجود ندارد')
        return redirect('staff:dashboard', username=request.user.username)

    if request.method == "POST":
        p_id = request.POST['professor']

        try:
            professor = Professor.objects.get(id=p_id)
        except ObjectDoesNotExist:
            messages.error(request, 'استاد مورد نظر در این گروه وجود ندارد')
            return redirect('professor:set_group_admin', id=id)
        Adminstrator(group=group, professor=professor).save()
        professor.professorfields.is_adminstrator = True
        group.has_admin                           = True
        professor.professorfields.save()
        group.save()
        messages.success(request, 'دکتر {first_name} {last_name} به عنوان مدیر گروه {title} انتخاب شدند.'.format(first_name=professor.first_name,
                                                                                                                last_name=professor.last_name,
                                                                                                                title=group.title))
        message = """استاد گرامی {first_name} {last_name} شما به عنوان مدیر گروه {title} تعیین شدید. \n
                    """.format(first_name=professor.first_name, 
                                last_name=professor.last_name,
                                title=group.title,) 

        send_mail(SUBJECT, 
                message, 
                EMAIL_HOST_USER, 
                [professor.email], 
                fail_silently=False)                                                                                            
        return redirect('staff:dashboard', username=request.user.username)
    context = {
        'group': group,
        'pfs': pfs
    }
        
    return render(request, 'staff/system/setGroupAdmin.html', context=context)        
    

@login_required
def addOrientation(request):

    user     = request.user 
    
    if user.item_type == User.Types.STAFF:
        college = user.stafffields.college
    else:
        return redirect('system:logout')

    if request.method == "POST":
        o_form = OrientationForm(request.POST)        

        if o_form.is_valid():
            group_id = request.POST.get('group')
            try:
                group = Group.objects.get(id=group_id)
            except ObjectDoesNotExist:
                return redirect('staff:dashboard', username=user.username)

            instance       = o_form.save(commit=False)
            instance.group = group
            instance.save()
            messages.success(request, 'گرایش اضافه شد')        
            return redirect('staff:dashboard', username=user.username)
    
    else:
        o_form  = OrientationForm()

    groups  = Group.objects.filter(college=college)
    context = {
        'o_form': o_form,
        'groups': groups
    }
    return render(request, 'staff/system/addOrientation.html', context=context)

@login_required
def groupOrientationList(request, id):
    if request.user.item_type != User.Types.STAFF:
        return redirect('system:logout')
    try:
        group = Group.objects.get(id=id)
    except:
        messages.error(request, 'گروه پیدا نشد!')
        return redirect('staff:dashboard', username=request.user.username)
    ors = Orientation.objects.filter(group=id)
    context = {
        'ors': ors,
        'group': group,
    }
    return render(request, 'staff/system/ors.html', context=context)


@login_required
def error(request):
    return render(request, 'staff/error.html', context=None)

@login_required
def groups(request):
    if request.user.item_type != User.Types.STAFF:
        messages.error(request, 'دسترسی ندارید!')
        return redirect('system:logout')
    else:
        pass

    try:
        clg    = request.user.stafffields.college
        groups = Group.objects.get(college=clg)
    except:
        return redirect('system:logout')
    return render(request, 'staff/system/groups.html', context={'groups': groups})

@login_required
def dashboard(request, username):
    if request.user.item_type != User.Types.STAFF:
        messages.error(request, 'دسترسی ندارید!')
        return redirect('system:logout')
    else:
        pass

    try:
        clg    = request.user.stafffields.college
        groups = Group.objects.filter(college=clg)
    except:
        return redirect('system:logout')
    return render(request, 'staff/dashboard.html', context={'groups': groups})




# @login_required
# def dashboard(request):

#     try:
#         user = UserModel.objects.get(id=request.user.id)
#     except ObjectDoesNotExist:
#         return HttpResponse("چنین کاربری نداریم")

#     if request.method == "POST" :
#         update_user_form   = UserUpdateForm(data=request.POST, instance=user)
#         update_avatar_form = AvatarUpdateForm(request.POST, request.FILES, instance=user.avatarmodel)

#         if update_user_form.is_valid() and update_avatar_form.is_valid():
#             update_avatar_form.save()
#             update_user_form.save()

#             messages.success(request, 'صفحه شما بروزرسانی شد.')        
#             return redirect('user:dashboard')

#     else:
#         update_user_form = UserUpdateForm(instance=user)
#         update_avatar_form = AvatarUpdateForm(instance=user.avatarmodel)

#     context = {
#         'user_form'  : update_user_form,
#         'avatar_form': update_avatar_form,   
#         'user'       : user,
#     }

#     return render(
#             request, 
#             'user/dashboard.html', 
#             context=context
#         )

masters/frontend/templates/staff/dashboard.html
{% extends './template.html' %}



{% block page_title %}
	داشبورد
{% endblock page_title %}
	


{% block panel_title %}
	لیست گروه های موجود در دانشکده {{ request.user.stafffields.college.title }}
{% endblock panel_title %}
	

{% block content %}
	<div class="x_content">
		<table class="table table-dark mt-5">
			<thead>
				<tr>
					<th scope="col" style="color: aquamarine;">عنوان</th>
					<th scope="col" style="color: aquamarine;">مدیر گروه</th>
					<th scope="col" style="color: aquamarine;">اساتید</th>
					<th scope="col" style="color: aquamarine;">گرایش ها</th>
					<th scope="col" style="color: aquamarine;">دانشجویان</th>
					<th scope="col" style="color: aquamarine;"></th>
				</tr>
			</thead>
			{% for group in groups %}
				<tr>
					<th scope="col"><p>{{ group.title }}</p></th>
					
					{% if group.has_admin %}
						<th scope="col">دکتر {{ group.adminstrator.professor.first_name }} {{ group.adminstrator.professor.last_name }}</th>				
					{% else %}
						<th scope="col"><a href="{% url 'staff:set_group_admin' id=group.id %}"><button class="btn btn-danger" title="مدیر گروه را تعیین کنید">تعیین مدیر گروه</button></a></th>
					{% endif %}
					<th scope="col"><a href="{% url 'staff:group_professor_list' id=group.id %}"><button class="btn btn-primary">اساتید</button></a></th>
					<th scope="col"><a href="{% url 'staff:group_orientation_list' id=group.id %}"><button class="btn btn-primary">گرایش ها</button></a></th>
					<th scope="col"><a href="{% url 'staff:group_student_list' id=group.id %}"><button class="btn btn-primary">دانشجویان</button></a></th>
					<th scope="col">
						<a href="{% url 'staff:edit_group' id=group.id %}" title="ویرایش"><i class="far fa-edit"></i></a>
						<a href="{% url 'staff:delete_group' id=group.id %}" title="حذف"><i class="far fa-trash"></i></a>
					</th>
				</tr>
			{% endfor %}
		</table>
	
	</div>



<!-- <div class="main">
	<h1>لیست گروه های دانشکده {{ request.user.stafffields.college.title }}</h1>
	<table class="table table.fit table-dark mt-5">
		<thead>
			<tr>
				<th scope="col" style="color: aquamarine;">عنوان</th>
				<th scope="col" style="color: aquamarine;">مدیر گروه</th>
				<th scope="col" style="color: aquamarine;">اساتید</th>
				<th scope="col" style="color: aquamarine;">گرایش ها</th>
				<th scope="col" style="color: aquamarine;">دانشجویان</th>
				<th scope="col" style="color: aquamarine;"></th>
			</tr>
		</thead>
		{% for group in groups %}
			<tr>
				<th scope="col"><p>{{ group.title }}</p></th>
				
				{% if group.has_admin %}
					<th scope="col">دکتر {{ group.adminstrator.professor.first_name }} {{ group.adminstrator.professor.last_name }}</th>				
				{% else %}
					<th scope="col"><a href="{% url 'staff:set_group_admin' id=group.id %}"><button class="btn btn-danger" title="مدیر گروه را تعیین کنید">تعیین مدیر گروه</button></a></th>
				{% endif %}
				<th scope="col"><a href="{% url 'staff:group_professor_list' id=group.id %}"><button class="btn btn-primary">اساتید</button></a></th>
				<th scope="col"><a href="{% url 'staff:group_professor_list' id=group.id %}"><button class="btn btn-primary">گرایش ها</button></a></th>
				<th scope="col"><a href="{% url 'staff:group_student_list' id=group.id %}"><button class="btn btn-primary">دانشجویان</button></a></th>
				<th scope="col">
					<a href="{% url 'staff:edit_group' id=group.id %}" title="ویرایش"><i class="far fa-edit"></i></a>
					<a href="{% url 'staff:delete_group' id=group.id %}" title="حذف"><i class="far fa-trash"></i></a>
				</th>
			</tr>
		{% endfor %}
	</table>
</div> -->
    
        
{% endblock content %}
    

masters/frontend/templates/staff/error.html
{% extends './template.html' %}


{% block content %}
    <h1>Error</h1>
{% endblock content %}
    

masters/frontend/templates/staff/sidebar.html
<!-- sidebar menu -->
<ul class="nav side-menu">
    <li><a><i class="fas fa-chalkboard-teacher fa-lg"></i>&nbsp; اساتید <span class="fa fa-chevron-left"></span></a>
            <ul class="nav child_menu">
                <li><a href="{% url 'staff:add_professor' %}">ایجاد حساب</a></li>
                <li><a href="{% url 'staff:professor_list' %}">لیست اساتید</a></li>
        </ul>
    </li>


    <li><a><i class="fa fa-graduation-cap"></i> دانشجویان 
        <span class="fa fa-chevron-left"></span></a>
        <ul class="nav child_menu">
            <li><a href="{% url 'staff:add_student' %}">ایجاد حساب</a></li>
            <li><a href="{% url 'staff:student_list' %}">لیست دانشجویان</a></li>
        </ul>
    </li>

    <li><a><i class="fas fa-chalkboard-teacher fa-lg"></i>&nbsp; گروه <span class="fa fa-chevron-left"></span></a>
        <ul class="nav child_menu">
            <li><a href="{% url 'staff:add_professor' %}">ایجاد حساب</a></li>
            <li><a href="{% url 'staff:professor_list' %}">لیست اساتید</a></li>
        </ul>
    </li>

    <li><a><i class="fa fa-file-alt"></i> درخواست ها <span class="fa fa-chevron-left"></span></a>
        <ul class="nav child_menu">
            <li><a href="chartjs.html">Chart JS</a></li>
            <li><a href="chartjs2.html">Chart JS2</a></li>
            <li><a href="morisjs.html">Moris JS</a></li>
            <li><a href="echarts.html">ECharts</a></li>
            <li><a href="other_charts.html">چارت های دیگر</a></li>
        </ul>
    </li>
    <li><a href="#"><i class="fa fa-laptop"></i> صفحه مقصد </a></li>

</ul>
<!-- /sidebar menu -->

masters/frontend/templates/staff/template.html
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../build/images/favicon.ico" type="image/ico"/>
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/bootstrap-rtl/dist/css/bootstrap-rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/nprogress/nprogress.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/iCheck/skins/flat/green.css' %}">
    <link rel="stylesheet" href="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.css' %}">
    <link rel="stylesheet" href="{% static 'build/css/custom.min.css' %}">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

</head>
<!-- /header content -->
<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <div class="col-md-3 left_col hidden-print">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="{% url 'staff:dashboard' username=request.user.username %}" class="site_title">تحصیلات تکمیلی</span></a>
                </div>

                <div class="clearfix"></div>

                <!-- menu profile quick info -->
                <div class="profile clearfix">
                    <div class="profile_pic">
                        <img src="{% static 'build/images/default.png' %}" alt="..." class="img-circle profile_img">
                    </div>
                    <div class="profile_info">
                        <span>خوش آمدید,</span>
                        <h2>{{ request.user.first_name }} {{ request.user.last_name }}</h2>
                    </div>
                </div>
                <!-- /menu profile quick info -->

                <br/>

                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <h3>سامانه اداری</h3>
                        {% include './sidebar.html' %}                    
                    </div>
                </div>
                <!-- /sidebar menu -->


                <!-- /menu footer buttons -->
                    {% include '../public/menuFooterButtons.html' %}
                <!-- /menu footer buttons -->
            </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav hidden-print">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>

                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                <img src="{% static 'build/images/default.png' %}" alt="">{{ request.user.first_name }} {{ request.user.last_name }}
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> خروج</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->
        <!-- /header content -->
        
<!-- page content -->
<div class="right_col" role="main">
    <div class="">

        <div class="page-title">
            <div class="title_left">
                <h4>{% block page_title %}{% endblock page_title %}</h4>
            </div>
        </div>

        <div class="clearfix"></div>

        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                    <div class="x_title">
                        <h2>{% block panel_title %}{% endblock panel_title %}</h2>
                        <ul class="nav navbar-right panel_toolbox">
                            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                            </li>
                            <li><a class="close-link"><i class="fa fa-close"></i></a>
                            </li>
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /page content -->



    </div>
</div>


<div id="lock_screen">
    <table>
        <tr>
            <td>
                <div class="clock"></div>
                <span class="unlock">
                    <span class="fa-stack fa-5x">
                      <i class="fa fa-square-o fa-stack-2x fa-inverse"></i>
                      <i id="icon_lock" class="fa fa-lock fa-stack-1x fa-inverse"></i>
                    </span>
                </span>
            </td>
        </tr>
    </table>
</div>

<script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
<script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
<script src="{% static 'vendors/bootstrap-progressbar/bootstrap-progressbar.min.js' %}"></script>
<script src="{% static 'vendors/iCheck/icheck.min.js' %}"></script>
<script src="{% static 'vendors/moment/min/moment.min.js' %}"></script>
<script src="{% static 'vendors/bootstrap-daterangepicker/daterangepicker.js' %}"></script>
<script src="{% static 'build/js/custom.min.js' %}"></script>
<script src="{% static 'build/js/more.js' %}"></script>

</body>
</html>