masters/masters/urls.py
from django.contrib import admin
from django.urls import path, include
from masters import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
    path('student/', include('student.urls')),
    path('professor/', include('professor.urls')),
    path('staff/', include('staff.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masters/professor/urls.py
from django.urls import path
from professor import views

app_name = "professor"

urlpatterns = [
    path('request/master/', views.masterRequest, name='request_master'),
    path('request/supervise/', views.superviseRequest, name='request_supervise'),
    path('jury/invite/', views.juryInvite, name='jury_invite'),
    path('<str:username>/', views.dashboard, name='dashboard'),
]

masters/staff/urls.py
from django.urls import path
from staff import views, professorView, studentView

app_name = 'staff'

urlpatterns = [
    # PROFESSOR CRUD
    path('add/professor/', professorView.addProfessor, name='add_professor'),
    path('professors/', professorView.addProfessor, name='professor_list'),
    path('professor/<int:id>/edit/', professorView.professorEdit, name='professor_edit'),
    
    # STUDENT CRUD
    path('student/<int:id>/edit/', studentView.studentEdit, name='student_edit'),
    path('add/student/', studentView.addStudent, name='add_student'),
    path('students/', studentView.addStudent, name='student_list'),
    
    # SYSTEM CRUD
    path('add/group/', views.addGroup, name='add_group'),
    path('group/admin/<int:id>', views.setGroupAdmin, name='set_group_admin'),
    path('add/orientation/', views.addOrientation, name='add_orientation'),
    path('group/<int:id>/edit/', views.editGroup, name='edit_group'),
    path('group/<int:id>/delete/', views.error, name='delete_group'),
    path('orientation/<int:id>/edit/', views.editOrientation, name='edit_orientation'),
    path('orientation/<int:id>/delete/', views.deleteOrientation, name='delete_orientation'),
    
    # GET
    path('groups/', views.groups, name='groups'),
    path('group/<int:id>/orientations/', views.groupOrientationList, name='group_orientation_list'),
    path('group/<int:id>/professors/', views.groups, name='group_professor_list'),
    path('group/<int:id>/students/', views.groups, name='group_student_list'),
    path('orientation/<int:id>/students/', views.groups, name='orientation_student_list'),
    path('error/', views.error, name='error'),
    path('<str:username>/', views.dashboard, name='dashboard'),
]

masters/professor/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager
from system.models import User, Group, Orientation

class Professor(User):
    class Meta:
        proxy = True

    class ProfessorManager(BaseUserManager):
        def get_queryset(self, *args, **kwargs):
            return super().get_queryset(*args, **kwargs).filter(item_type=User.Types.PROFESSOR)

    def save(self, *args, **kwargs):
        self.item_type = User.Types.PROFESSOR
        return super().save(*args, **kwargs)


    objects = ProfessorManager()

    @property
    def fields(self):
        return self.professorfields

class ProfessorFields(models.Model):

    class Grades(models.TextChoices):
        INSTRUCTOR = 0
        ASSISTANT  = 1
        ASSOCIATE  = 2
        PROFESSOR  = 3

    professor       = models.OneToOneField(Professor, on_delete=models.CASCADE)
    is_adminstrator = models.BooleanField(default=False)
    grade           = models.CharField(max_length=10, choices=Grades.choices)
    last_university = models.CharField(max_length=100)
    objects         = models.Manager()
    # RELATIONS
    group           = models.ForeignKey(Group, on_delete=models.DO_NOTHING)


class PHDRequest(models.Model):
    class Status(models.IntegerChoices):
       REJECTED    = 0 
       ACCEPTED    = 1
       IN_PROGRESS = 2

    request_id = models.CharField(max_length=10, blank=True)
    status     = models.IntegerField(choices=Status.choices, default=Status.IN_PROGRESS)
    clause_a   = models.JSONField()
    clause_b   = models.CharField(max_length=20)
    created_at = models.DateField(auto_now_add=True)
    manager_ok = models.BooleanField(default=False)
    staff_ok   = models.BooleanField(default=False)
    objects    = models.Manager() 
    
    # RELATIONS
    professor  = models.ForeignKey(Professor, on_delete=models.CASCADE)

class MasterRequest(models.Model):
    class Status(models.IntegerChoices):
       REJECTED    = 0 
       ACCEPTED    = 1
       IN_PROGRESS = 2

    request_id  = models.CharField(max_length=10, blank=True)
    status      = models.IntegerField(choices=Status.choices, default=Status.IN_PROGRESS)
    type_1      = models.SmallIntegerField()
    type_2      = models.SmallIntegerField()
    created_at  = models.DateField(auto_now_add=True)
    manager_ok  = models.BooleanField(default=False)
    staff_ok    = models.BooleanField(default=False)
    objects     = models.Manager() 

    # RELATIONS
    orientation = models.ForeignKey(Orientation, on_delete=models.DO_NOTHING)
    professor   = models.ForeignKey(Professor, on_delete=models.DO_NOTHING)

masters/system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField 

class College(models.Model):
    title   = models.CharField(max_length=100, unique=True)
    objects = models.Manager() 


class Group(models.Model):
    title     = models.CharField(max_length=100, unique=True)
    has_admin = models.BooleanField(default=False)
    objects   = models.Manager() 

    # RELATIONS
    college   = models.ForeignKey(College, on_delete=models.CASCADE)

    @property
    def adminstrator(self):
        return self.adminstrator

class Adminstrator(models.Model):
    professor = models.ForeignKey(to='professor.Professor', on_delete=models.DO_NOTHING)
    group     = models.OneToOneField(Group, primary_key=True, on_delete=models.CASCADE)


class Orientation(models.Model):
    title   = models.CharField(max_length=100, unique=True)
    objects = models.Manager() 
    
    # RELATIONS
    group   = models.ForeignKey(Group, on_delete=models.CASCADE)

class User(AbstractUser):
    
    class Gender(models.IntegerChoices):
        FEMALE = 0
        MALE   = 1
        NONE   = 2
    
    class Types(models.IntegerChoices):
        STUDENT   = 0
        PROFESSOR = 1
        STAFF     = 2
        OTHER     = 3

    first_name = models.CharField(max_length=30, blank=False)
    last_name  = models.CharField(max_length=30, blank=False)
    password   = models.CharField(max_length=100, blank=False)
    email      = models.EmailField(unique=False)
    username   = models.CharField(unique=True, max_length=10)
    n_code     = models.CharField(unique=True, max_length=10)
    phone      = PhoneNumberField(blank=False)
    item_type  = models.IntegerField(choices=Types.choices, default=Types.OTHER)
    is_staff   = models.BooleanField(default=False)
    gender     = models.IntegerField(choices=Gender.choices, default=Gender.NONE)
    created_at = models.DateField(auto_now_add=True, blank=True)
    is_active  = models.BooleanField(default=True)

    REQUIRED_FIELDS = ['n_code']

    def save(self, *args, **kwargs):
        print(self.password)
        if not self.is_superuser:
            if not self.password:
                print("password is None")
                self.set_password(self.n_code)
            else:
                print("password is not None")
                self.set_password(self.password)
        print(self.password)
            
        return super().save(*args, **kwargs)



class JuryInvitation(models.Model):
    class Status(models.IntegerChoices):
       REJECTED    = 0 
       ACCEPTED    = 1
       IN_PROGRESS = 2
    status     = models.IntegerField(choices=Status.choices, default=Status.IN_PROGRESS)
    created_at = models.DateField(auto_now_add=True)
    jury_date  = models.DateField()
    objects    = models.Manager()
    
    # RELATIONS
    professor  = models.ForeignKey(to="professor.Professor", on_delete=models.DO_NOTHING)
    disserta   = models.ForeignKey(to='student.Dissertation', on_delete=models.DO_NOTHING)


class Supervisor(models.Model):
    class Percent(models.IntegerChoices):
        Q1   = 25
        HALF = 50
        Q3   = 75
        FULL = 100
    student   = models.ForeignKey(to="student.Student", on_delete=models.DO_NOTHING, related_name="student")
    professor = models.ForeignKey(to="professor.Professor", on_delete=models.DO_NOTHING, related_name="professor")
    percent   = models.IntegerField(choices=Percent.choices, default=Percent.FULL)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['student', 'professor'], name="supervisor")
        ]
  

masters/professor/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField
from professor.models import Professor, ProfessorFields, MasterRequest


class ProfessorForm(forms.ModelForm):


    class Meta:
        model  = Professor
        fields = ['first_name', 'last_name', 'username', 'n_code', 'email', 'phone', 'gender']


    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if first_name.isdigit():
            raise forms.ValidationError('نوع ورودی نامعتبر')
        return first_name


    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if last_name.isdigit():
            raise forms.ValidationError('نوع ورودی نامعتبر')
        return last_name

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username) != 10:
            raise forms.ValidationError('شماره دانشجویی ۱۰ رقم است!')
        if not username.isdigit():
            raise forms.ValidationError('شماره دانشجویی عدد است!')
        return username

    def clean_n_code(self):
        n_code = self.cleaned_data.get('n_code')
        if len(n_code) != 10:
            raise forms.ValidationError('کدملی ۱۰ رقم است!')
        if not n_code.isdigit():
            raise forms.ValidationError('کدملی عدد است!')
        return n_code


class PFForm(forms.ModelForm):
    class Meta:
        model  = ProfessorFields
        fields = ['grade', 'last_university']

class MRForm(forms.ModelForm):
    class Meta:
        model  = MasterRequest
        fields = ['type_1', 'type_2']

    def clean_type_1(self):
        type_1 = self.cleaned_data.get('type_1')
        # if not type_1.isdigit():
        #     raise forms.ValidationError('لطفا عدد وارد کنید')
        if type_1 > 15:
            raise forms.ValidationError('بیشتر از حد مجاز')
        return type_1



    def clean_type_2(self):
        type_2 = self.cleaned_data.get('type_2')
        # if not type_2.isdigit():
        #     raise forms.ValidationError('لطفا عدد وارد کنید')
        if type_2 > 15:
            raise forms.ValidationError('بیشتر از حد مجاز')
        return type_2

# class StudentForm(forms.ModelForm):

#     # GENDER = (
#     #     ('female', 'مونث'),
#     #     ('male', 'مذکر'),
#     #     ('none', 'سایر'),
#     # )

#     # first_name = forms.CharField(label='نام', max_length=30, required=True)
#     # last_name  = forms.CharField(label='نام خانوادگی', max_length=30, required=True)
#     # username   = forms.CharField(label='نام کاربری(کد دانشجویی، کد پرسنلی)', max_length=30, required=False)
#     # n_code     = forms.CharField(label='کد ملی', required=True)
#     # email      = forms.EmailField(label='ایمیل', required=True)
#     # phone      = PhoneNumberField(required=True, required=True)
#     # college    = forms.CharField(max_length=20, required=True)
#     # item_type  = forms.CharField(max_length=10, required=True)
#     # gender     = forms.ChoiceField(choices=GENDER, required=True)


#     class Meta:
#         model  = Student
#         fields = ['first_name', 'last_name', 'username', 'n_code', 'email', 'phone', 'college', 'item_type', 'gender']
#         # fields = "__all__"

#     def clean_username(self):
#         username = self.cleaned_data.get('username')
#         if len(username) != 10:
#             raise forms.ValidationError('شماره دانشجویی ۱۰ رقم است!')
#         if not username.isdigit():
#             raise forms.ValidationError('شماره دانشجویی عدد است!')
#         return username

#     def clean_n_code(self):
#         n_code = self.cleaned_data.get('n_code')
#         if len(n_code) != 10:
#             raise forms.ValidationError('کدملی ۱۰ رقم است!')
#         if not n_code.isdigit():
#             raise forms.ValidationError('کدملی عدد است!')
#         return n_code


# class SFForm(forms.Form):
#     class Meta:
#         model  = StudentFields
#         fields = ['is_daily', 'last_university']


# class UserUpdateForm(UserForm):
#     about_me = RichTextFormField(max_length=700)

#     def __init__(self, *args, **kwargs):
#         super(UserUpdateForm, self).__init__(*args, **kwargs)
#         self.fields['email'].disabled = True
#         # self.fields.pop('password')

#     class Meta(UserForm.Meta):
#         fields = ['about_me', 'first_name', 'last_name', 'username', 'email', 'gender']

# class AvatarUpdateForm(forms.ModelForm):
#     class Meta:
#         model  = AvatarModel
#         fields = ['avatar']


# class ResetPasswordForm(forms.Form):
#     password       = forms.CharField(widget=forms.PasswordInput())
#     password_check = forms.CharField(widget=forms.PasswordInput())


#     def clean(self):
#         cleaned_data   = super().clean()
#         password       = cleaned_data.get('password')
#         password_check = cleaned_data.get('password_check')

#         if len(password) < 8:
#             raise forms.ValidationError('حداقل ۸ کاراکتر لازمه...')


#         if password != password_check:
#             raise forms.ValidationError('گذرواژه ها با هم همخوان نیست...')


#         # check for digit
#         if not any(char.isdigit() for char in password):
#             raise forms.ValidationError(('حداقل ۱ عدد باید داشته باشه...'))

#         # check for letter
#         if not any(char.isalpha() for char in password):
#             raise forms.ValidationError(('...حداقل ۱ حرف باید داشته باشه'))

#         return password

        


# class GetEmailForm(forms.Form):
#     email = forms.EmailField(required=True)

masters/professor/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required 
from system.views import logoutView, loginView
from system.models import User
from django.contrib import messages
from professor.forms import MRForm
from professor.models import MasterRequest
from django.core.exceptions import ObjectDoesNotExist


# def checkUser(request):
#     if request.user.item_type != User.Types.PROFESSOR:
#         messages.error(request, 'Access denied!')
#         return redirect('system:logout')
#     else:
#         pass

# Create your views here.
# def PHDRequest(request):
#     checkUser(request)
#     return render(request, 'professor/PHDRequest.html', {})

# @login_required
# def PHDRequest(request):
#     if request.user.item_type != User.Types.PROFESSOR:
#         messages.error(request, 'Access denied!')
#         return redirect('system:logout')
#     else:
#         pass
#     if request.method == "POST":
#         form = MRForm(request.POST)
#         if form.is_valid():
#             user = request.user
            
#     return render(request, 'professor/masterRequest.html', {})


# @login_required
# def setGroupAdmin(request, id):
#     if request.user.item_type != User.Types.PROFESSOR:
#         messages.error(request, 'Access denied!')
#         return redirect('system:logout')
#     if request.method == "POST":



@login_required
def masterRequest(request):
    if request.user.item_type != User.Types.PROFESSOR:
        messages.error(request, 'Access denied!')
        return redirect('system:logout')
    else:
        pass
    if request.method == "POST":
        form = MRForm(request.POST)
        if form.is_valid():
            instance           = form.save(commit=False)
            instance.professor = request.user
            instance.group     = request.user.professorfields.group
            instance.save()
            messages.success(request, 'درخواست با موفقیت ثبت شد. درخواست باید توسط مدیر گروه تائید شود!')
            return redirect('professor:dashboard', username=request.user.username)
    else:
        form = MRForm()
    try:
        MasterRequest.objects.get(professor=request.user)
        has = True
    except ObjectDoesNotExist:
        has = False
    context = {
        'form': form,
        'has': has
    }

    return render(request, 'professor/masterRequest.html', context=context)


@login_required
def superviseRequest(request):
    if request.user.item_type != User.Types.PROFESSOR:
        messages.error(request, 'Access denied!')
        return redirect('system:logout')
    else:
        pass
    return render(request, 'professor/superviseRequest.html', {})

@login_required
def juryInvite(request):
    if request.user.item_type != User.Types.PROFESSOR:
        messages.error(request, 'Access denied!')
        return redirect('system:logout')
    else:
        pass
    return render(request, 'professor/juryInvite.html', {})

@login_required
def dashboard(request, username):
    if request.user.item_type != User.Types.PROFESSOR:
        messages.error(request, 'Access denied!')
        return redirect('system:logout')
    
    return render(request, 'professor/dashboard.html', {})

masters/frontend/templates/staff/professor/addProfessor.html
{% extends '../template.html' %}



{% block panel_title %}
    ایجاد حساب اساتید دانشکده {{ request.user.stafffields.college.title }}
{% endblock panel_title %}
    

{% block content %}

            <div class="x_content">
                <br/>
                <form method="POST" class="form-horizontal form-label-left input_mask">
                    {% csrf_token %}

                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                            <input type="text" class="form-control has-feedback-left" id="id_first_name" name="first_name" placeholder="نام">
                            {{ form.first_name.errors }}
                            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                        </div>

                        <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                            <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="نام خانوادگی">
                            <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                            {{ form.last_name.errors }}
                        </div>

                        <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                            <input type="text" class="form-control has-feedback-left" id="id_email" name="email" placeholder="ایمیل">
                            <span class="fa fa-envelope form-control-feedback left" aria-hidden="true"></span>
                            {{ form.email.errors }}
                        </div>

                        <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                            <input type="text" class="form-control" id="id_phone" name="phone" pattern="+98-[0-9]{3}-[0-9]{7}" placeholder="تلفن">
                            <span class="fa fa-phone form-control-feedback left" aria-hidden="true"></span>
                            {{ form.phone.errors }}
                        </div>

                        <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                            <input type="text" class="form-control" id="id_n_code" name="n_code" placeholder="کد ملی">
                            <span class="fa fa-id-card form-control-feedback left" aria-hidden="true"></span>
                            {{ form.n_code.errors }}
                        </div>

                        <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                            <input type="text" class="form-control" id="id_username" name="username" placeholder="کد پرسنلی">
                            <span class="fa fa-id-card form-control-feedback left" aria-hidden="true"></span>
                            {{ form.username.errors }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-! col-xs-12">آخرین دانشگاه محل تحصیل</label>
                        <div class="col-md-9 col-sm-9 col-xs-12">
                            <input type="text" id="id_last_university" name="last_university" class="form-control" required>
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">گروه آموزشی</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select name="group" id="id_group">
                                {% for group in groups %}
                                    <option value="{{ group.id }}">{{ group.title }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">رتبه علمی</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select name="grade" id="id_grade">
                                <option value="INSTRUCTOR">مربی آموزشیار</option>
                                <option value="ASSISTANT">استادیار</option>
                                <option value="ASSOCIATE">دانشیار</option>
                                <option value="PROFESSOR">استاد تمام</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">جنسیت</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select name="gender" id="id_gender">
                                <option value="0">مونث</option>
                                <option value="1">مذکر</option>
                                <option value="2">سایر</option>
                            </select>
                        </div>
                        {{ form.gender.errors }}
                    </div>


                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                            <!-- <button type="submit" class="btn btn-primary">انصراف</button> -->
                            <button type="submit" class="btn btn-success">ارسال</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}