masters/masters/urls.py
from django.contrib import admin
from django.urls import path, include
from masters import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
    path('student/', include('student.urls')),
    path('professor/', include('professor.urls')),
    path('staff/', include('staff.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masters/staff/urls.py
from django.urls import path
from staff import views, professorView, studentView

app_name = 'staff'

urlpatterns = [
    # PROFESSOR CRUD
    path('add/professor/', professorView.addProfessor, name='add_professor'),
    path('professors/', professorView.addProfessor, name='professor_list'),
    path('professor/<int:id>/edit/', professorView.professorEdit, name='professor_edit'),
    
    # STUDENT CRUD
    path('student/<int:id>/edit/', studentView.studentEdit, name='student_edit'),
    path('add/student/', studentView.addStudent, name='add_student'),
    path('students/', studentView.addStudent, name='student_list'),
    
    # SYSTEM CRUD
    path('add/group/', views.addGroup, name='add_group'),
    path('group/admin/<int:id>', views.setGroupAdmin, name='set_group_admin'),
    path('add/orientation/', views.addOrientation, name='add_orientation'),
    path('group/<int:id>/edit/', views.editGroup, name='edit_group'),
    path('group/<int:id>/delete/', views.error, name='delete_group'),
    path('orientation/<int:id>/edit/', views.editOrientation, name='edit_orientation'),
    path('orientation/<int:id>/delete/', views.deleteOrientation, name='delete_orientation'),
    
    # GET
    path('groups/', views.groups, name='groups'),
    path('group/<int:id>/orientations/', views.groupOrientationList, name='group_orientation_list'),
    path('group/<int:id>/professors/', views.groups, name='group_professor_list'),
    path('group/<int:id>/students/', views.groups, name='group_student_list'),
    path('orientation/<int:id>/students/', views.groups, name='orientation_student_list'),
    path('error/', views.error, name='error'),
    path('<str:username>/', views.dashboard, name='dashboard'),
]

masters/system/urls.py
from django.urls import path, include
# from django.contrib.auth import views as auth_views
from system import views

app_name = 'system'

urlpatterns = [
    # user Authentication
    path('', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),


    # # CRUD
    # path('createuser/', views.createEmployee, name='createEmployee'),
    # path('find/', views.find, name='find'),
    # path('update/<slug:p_id>', views.updateEmployee, name='updateEmployee'),
    # path('destroy/<slug:p_id>', views.destroy, name='destroy'),
    # # APIs
    # path('employeeslist/', views.employees_list, name='employeeslist'),
    # path('updatesalary/<slug:p_id>/<int:value>', views.update_salary, name='updatesalary'),
    # path('listbyname/<slug:name>', views.list_by_name, name='listbyname'),
    # path('deletebygender/<slug:gender>', views.delete_by_gender, name='deletebtgender'),
]

masters/system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField 

class College(models.Model):
    title   = models.CharField(max_length=100, unique=True)
    objects = models.Manager() 


class Group(models.Model):
    title     = models.CharField(max_length=100, unique=True)
    has_admin = models.BooleanField(default=False)
    objects   = models.Manager() 

    # RELATIONS
    college   = models.ForeignKey(College, on_delete=models.CASCADE)

    @property
    def adminstrator(self):
        return self.adminstrator

class Adminstrator(models.Model):
    professor = models.ForeignKey(to='professor.Professor', on_delete=models.DO_NOTHING)
    group     = models.OneToOneField(Group, primary_key=True, on_delete=models.CASCADE)


class Orientation(models.Model):
    title   = models.CharField(max_length=100, unique=True)
    objects = models.Manager() 
    
    # RELATIONS
    group   = models.ForeignKey(Group, on_delete=models.CASCADE)

class User(AbstractUser):
    
    class Gender(models.IntegerChoices):
        FEMALE = 0
        MALE   = 1
        NONE   = 2
    
    class Types(models.IntegerChoices):
        STUDENT   = 0
        PROFESSOR = 1
        STAFF     = 2
        OTHER     = 3

    first_name = models.CharField(max_length=30, blank=False)
    last_name  = models.CharField(max_length=30, blank=False)
    password   = models.CharField(max_length=100, blank=False)
    email      = models.EmailField(unique=False)
    username   = models.CharField(unique=True, max_length=10)
    n_code     = models.CharField(unique=True, max_length=10)
    phone      = PhoneNumberField(blank=False)
    item_type  = models.IntegerField(choices=Types.choices, default=Types.OTHER)
    is_staff   = models.BooleanField(default=False)
    gender     = models.IntegerField(choices=Gender.choices, default=Gender.NONE)
    created_at = models.DateField(auto_now_add=True, blank=True)
    is_active  = models.BooleanField(default=True)

    REQUIRED_FIELDS = ['n_code']

    def save(self, *args, **kwargs):
        print(self.password)
        if not self.is_superuser:
            if not self.password:
                print("password is None")
                self.set_password(self.n_code)
            else:
                print("password is not None")
                self.set_password(self.password)
        print(self.password)
            
        return super().save(*args, **kwargs)



class JuryInvitation(models.Model):
    class Status(models.IntegerChoices):
       REJECTED    = 0 
       ACCEPTED    = 1
       IN_PROGRESS = 2
    status     = models.IntegerField(choices=Status.choices, default=Status.IN_PROGRESS)
    created_at = models.DateField(auto_now_add=True)
    jury_date  = models.DateField()
    objects    = models.Manager()
    
    # RELATIONS
    professor  = models.ForeignKey(to="professor.Professor", on_delete=models.DO_NOTHING)
    disserta   = models.ForeignKey(to='student.Dissertation', on_delete=models.DO_NOTHING)


class Supervisor(models.Model):
    class Percent(models.IntegerChoices):
        Q1   = 25
        HALF = 50
        Q3   = 75
        FULL = 100
    student   = models.ForeignKey(to="student.Student", on_delete=models.DO_NOTHING, related_name="student")
    professor = models.ForeignKey(to="professor.Professor", on_delete=models.DO_NOTHING, related_name="professor")
    percent   = models.IntegerField(choices=Percent.choices, default=Percent.FULL)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['student', 'professor'], name="supervisor")
        ]
  

masters/staff/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.conf import settings
# from django.views import View

from staff.forms import UserForm, GroupForm, OrientationForm
from system.models import Group, User, Orientation, Adminstrator
from professor.models import Professor, ProfessorFields
from student.models import Student, StudentFields
from masters.settings import EMAIL_HOST_USER
from django.core.mail import send_mail


SUBJECT = 'تحصیلات تکمیلی دانشگاه بوعلی سینا'



@login_required
def addGroup(request):
    if request.user.item_type != User.Types.STAFF:
        messages.error(request, 'دسترسی ندارید!')
        return redirect('system:logout')

    if request.method == "POST":
        form = GroupForm(request.POST)        
        if form.is_valid():
            instance = form.save(commit=False)
            user     = request.user 
            college  = ''
            if user.item_type == User.Types.STAFF:
                college = user.stafffields.college
            else:
                return redirect('system:logout')
            instance.college = college
            instance.save()
            messages.success(request, 'گروه اضافه شد')        
            return redirect('staff:dashboard', username=user.username)
    else:
        form = GroupForm()
    
    return render(request, 'staff/system/addGroup.html', {'form': form})



@login_required
def editGroup(request, id):

    return render(request, 'staff/error.html', context=None)



@login_required
def editOrientation(request, id):

    return render(request, 'staff/error.html', context=None)


@login_required
def deleteOrientation(request, id):

    return render(request, 'staff/error.html', context=None)



@login_required
def setGroupAdmin(request, id):
    if request.user.item_type != User.Types.STAFF:
        messages.error(request, 'Access denied!')
        return redirect('system:logout')
    try:
        group = Group.objects.get(id=id)
        pfs   = ProfessorFields.objects.filter(group=group)
    except ObjectDoesNotExist:
        messages.error(request, 'گروه مورد نظر وجود ندارد')
        return redirect('staff:dashboard', username=request.user.username)

    if request.method == "POST":
        p_id = request.POST['professor']

        try:
            professor = Professor.objects.get(id=p_id)
        except ObjectDoesNotExist:
            messages.error(request, 'استاد مورد نظر در این گروه وجود ندارد')
            return redirect('professor:set_group_admin', id=id)
        Adminstrator(group=group, professor=professor).save()
        professor.professorfields.is_adminstrator = True
        group.has_admin                           = True
        professor.professorfields.save()
        group.save()
        messages.success(request, 'دکتر {first_name} {last_name} به عنوان مدیر گروه {title} انتخاب شدند.'.format(first_name=professor.first_name,
                                                                                                                last_name=professor.last_name,
                                                                                                                title=group.title))
        message = """استاد گرامی {first_name} {last_name} شما به عنوان مدیر گروه {title} تعیین شدید. \n
                    """.format(first_name=professor.first_name, 
                                last_name=professor.last_name,
                                title=group.title,) 

        send_mail(SUBJECT, 
                message, 
                EMAIL_HOST_USER, 
                [professor.email], 
                fail_silently=False)                                                                                            
        return redirect('staff:dashboard', username=request.user.username)
    context = {
        'group': group,
        'pfs': pfs
    }
        
    return render(request, 'staff/system/setGroupAdmin.html', context=context)        
    

@login_required
def addOrientation(request):

    user     = request.user 
    
    if user.item_type == User.Types.STAFF:
        college = user.stafffields.college
    else:
        return redirect('system:logout')

    if request.method == "POST":
        o_form = OrientationForm(request.POST)        

        if o_form.is_valid():
            group_id = request.POST.get('group')
            try:
                group = Group.objects.get(id=group_id)
            except ObjectDoesNotExist:
                return redirect('staff:dashboard', username=user.username)

            instance       = o_form.save(commit=False)
            instance.group = group
            instance.save()
            messages.success(request, 'گرایش اضافه شد')        
            return redirect('staff:dashboard', username=user.username)
    
    else:
        o_form  = OrientationForm()

    groups  = Group.objects.filter(college=college)
    context = {
        'o_form': o_form,
        'groups': groups
    }
    return render(request, 'staff/system/addOrientation.html', context=context)

@login_required
def groupOrientationList(request, id):
    if request.user.item_type != User.Types.STAFF:
        return redirect('system:logout')
    try:
        group = Group.objects.get(id=id)
    except:
        messages.error(request, 'گروه پیدا نشد!')
        return redirect('staff:dashboard', username=request.user.username)
    ors = Orientation.objects.filter(group=id)
    context = {
        'ors': ors,
        'group': group,
    }
    return render(request, 'staff/system/ors.html', context=context)


@login_required
def error(request):
    return render(request, 'staff/error.html', context=None)

@login_required
def groups(request):
    if request.user.item_type != User.Types.STAFF:
        messages.error(request, 'دسترسی ندارید!')
        return redirect('system:logout')
    else:
        pass

    try:
        clg    = request.user.stafffields.college
        groups = Group.objects.get(college=clg)
    except:
        return redirect('system:logout')
    return render(request, 'staff/system/groups.html', context={'groups': groups})

@login_required
def dashboard(request, username):
    if request.user.item_type != User.Types.STAFF:
        messages.error(request, 'دسترسی ندارید!')
        return redirect('system:logout')
    else:
        pass

    try:
        clg    = request.user.stafffields.college
        groups = Group.objects.filter(college=clg)
    except:
        return redirect('system:logout')
    return render(request, 'staff/dashboard.html', context={'groups': groups})




# @login_required
# def dashboard(request):

#     try:
#         user = UserModel.objects.get(id=request.user.id)
#     except ObjectDoesNotExist:
#         return HttpResponse("چنین کاربری نداریم")

#     if request.method == "POST" :
#         update_user_form   = UserUpdateForm(data=request.POST, instance=user)
#         update_avatar_form = AvatarUpdateForm(request.POST, request.FILES, instance=user.avatarmodel)

#         if update_user_form.is_valid() and update_avatar_form.is_valid():
#             update_avatar_form.save()
#             update_user_form.save()

#             messages.success(request, 'صفحه شما بروزرسانی شد.')        
#             return redirect('user:dashboard')

#     else:
#         update_user_form = UserUpdateForm(instance=user)
#         update_avatar_form = AvatarUpdateForm(instance=user.avatarmodel)

#     context = {
#         'user_form'  : update_user_form,
#         'avatar_form': update_avatar_form,   
#         'user'       : user,
#     }

#     return render(
#             request, 
#             'user/dashboard.html', 
#             context=context
#         )

masters/system/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.conf import settings
from django.views.generic import View

from system.forms import *
from system.models import User


def home(request):
    return render(request, 'error.html', {})

def whichApp(request, user):
    if user.item_type == User.Types.PROFESSOR:
        return redirect('professor:dashboard', username=user.username)
    elif user.item_type == User.Types.STUDENT:
        return redirect('student:dashboard', username=user.username)
    elif user.item_type == User.Types.STAFF:
        return redirect('staff:dashboard', username=user.username)
    else:
        return render(request, 'error.html', {})


def loginView(request):

    user = request.user
    if user.is_authenticated:
        return whichApp(request, user)
        
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, 
                            password=password)
        if user:
            login(request, user)
            request.session['id'] = user.id
            messages.success(request, 'سلام '+str(user.username)) 
            return whichApp(request, user)

        else:
            return render(request, 'error.html', {})

    return render(request, 'system/login.html', {})


@login_required
def logoutView(request):
    try:
        request.session.delete()
        logout(request)
    except KeyError:
        return redirect('system:users')
    return redirect('system:login')




# class ResetPasswordView(View):
#     form_class = ResetPasswordForm
#     template   = settings.EMAIL_RESET_PASSWORD_TEMPLATE

#     def get(self, request, *args, **kwargs):
#         email       = self.kwargs['email']
#         email_token = self.kwargs['email_token']

#         if verifyToken(email, email_token):
#             form = self.form_class()
#             return render(request, self.template, {'form': form})
#         else:
#             return redirect('user:login')

#     def post(self, request, *args, **kwargs):
#         form     = self.form_class(request.POST)
#         username = self.kwargs['username']

#         if form.is_valid():
#             try:
#                 user = UserModel.objects.get(username=username)
#                 user.set_password(form.cleaned_data) # Deactivate account till it is confirmed
#                 user.save()

#                 messages.success(request, ('لطفا برای تکمیل ثبت نام ایمیل خودتون رو تایید کنید.'))
#                 return redirect('user:login')

#             except ObjectDoesNotExist:
#                 return redirect('user:login')

#         else:
#             return render(request, self.template, {'form': form})

masters/frontend/templates/staff/system/addGroup.html
{% extends '../template.html' %}


{% block page_title %}
    
{% endblock page_title %}
    

{% block content %}
<form method="post" class="form-horizontal form-label-left input_mask">
    {% csrf_token %}

    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">عنوان گروه</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" name="title" placeholder="عنوان گروه" required >
        </div>
    </div>
            

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                <!-- <button type="submit" class="btn btn-primary">انصراف</button> -->
                <button type="submit" class="btn btn-success">ثبت</button>
            </div>
        </div>
    </div>
</form>

{% endblock content %}
    

masters/frontend/templates/staff/system/addOrientation.html
{% extends '../template.html' %}


{% block page_title %}
    
{% endblock page_title %}
    

{% block content %}
<form method="post" class="form-horizontal form-label-left input_mask">
    {% csrf_token %}

    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">عنوان گرایش</label>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <input type="text" name="title" placeholder="عنوان گرایش" required >
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">گروه</label>
        {% if not groups %}
            <div class="col-md-9 col-sm-9 ">
                <p>ابتدا باید گروه ایجاد کنید</p>
                <button type="button" class="btn btn-primary">
                    <a href="{% url 'staff:add_group' %}" style="color: aliceblue; text-decoration-style: none;">ایجاد گروه</a>
                </button>
            </div>
        {% else %}
        <div class="col-md-6 col-sm-6 col-xs-12">
            <select name="group" id="id_group">
                    {% for group in groups %}
                        <option value="{{ group.id }}">{{ group.title }}</option>
                    {% endfor %}
                </select>
            </div>
        {% endif %}
            

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                <!-- <button type="submit" class="btn btn-primary">انصراف</button> -->
                <button type="submit" class="btn btn-success">ارسال</button>
            </div>
        </div>
    </div>
</form>
    <!-- <form method="post">
        {% csrf_token %}
        <input type="text" name="title" placeholder="عنوان گرایش" required >
        <select name="group" id="group" required>
            {% for group in groups %}
                <option value="{{ group.id }}">{{ group.title }}</option>
            {% endfor %}
        </select>
        <button type="submit">ثبت</button>
    </form> -->
{% endblock content %}
    

masters/frontend/templates/staff/system/groups.html
{% extends './template.html' %}



{% block page_title %}
	گروه ها
{% endblock page_title %}
	


{% block panel_title %}
	لیست گروه های موجود در دانشکده {{ request.user.stafffields.college.title }}
{% endblock panel_title %}
	

{% block content %}
	<div class="x_content">
		<table class="table table-dark mt-5">
			<thead>
				<tr>
					<th scope="col" style="color: aquamarine;">عنوان</th>
					<th scope="col" style="color: aquamarine;">مدیر گروه</th>
					<th scope="col" style="color: aquamarine;">اساتید</th>
					<th scope="col" style="color: aquamarine;">گرایش ها</th>
					<th scope="col" style="color: aquamarine;">دانشجویان</th>
					<th scope="col" style="color: aquamarine;"></th>
				</tr>
			</thead>
			{% for group in groups %}
				<tr>
					<th scope="col"><p>{{ group.title }}</p></th>
					
					{% if group.has_admin %}
						<th scope="col">دکتر {{ group.adminstrator.professor.first_name }} {{ group.adminstrator.professor.last_name }}</th>				
					{% else %}
						<th scope="col"><a href="{% url 'staff:set_group_admin' id=group.id %}"><button class="btn btn-danger" title="مدیر گروه را تعیین کنید">تعیین مدیر گروه</button></a></th>
					{% endif %}
					<th scope="col"><a href="{% url 'staff:group_professor_list' id=group.id %}"><button class="btn btn-primary">اساتید</button></a></th>
					<th scope="col"><a href="{% url 'staff:group_orientation_list' id=group.id %}"><button class="btn btn-primary">گرایش ها</button></a></th>
					<th scope="col"><a href="{% url 'staff:group_student_list' id=group.id %}"><button class="btn btn-primary">دانشجویان</button></a></th>
					<th scope="col">
						<a href="{% url 'staff:edit_group' id=group.id %}" title="ویرایش"><i class="far fa-edit"></i></a>
						<a href="{% url 'staff:delete_group' id=group.id %}" title="حذف"><i class="far fa-trash"></i></a>
					</th>
				</tr>
			{% endfor %}
		</table>
	
	</div>

    
{% endblock content %}
    

masters/frontend/templates/staff/system/ors.html
{% extends '../template.html' %}




{% block panel_title %}
	لیست گروه های موجود در دانشکده {{ request.user.stafffields.college.title }}
{% endblock panel_title %}
	

{% block content %}
	<div class="x_content">
		
		{% if ors %}
			<table class="table table-light mt-2">
				<thead>
					<tr>
						<th scope="col" style="color: aquamarine;">عنوان</th>
						<th scope="col" style="color: aquamarine;">دانشجویان</th>
						<th scope="col" style="color: aquamarine;"></th>
					</tr>
				</thead>
				{% for item in ors %}
					<tr>
						<th scope="col"><p>{{ item.title }}</p></th>					
						<th scope="col"><a href="{% url 'staff:orientation_student_list' id=item.id %}"><button class="btn btn-primary">دانشجویان</button></a></th>
						<th scope="col">
							<a href="{% url 'staff:edit_orientation' id=item.id %}" title="ویرایش"><i class="far fa-edit"></i></a>
							<a href="{% url 'staff:delete_orientation' id=item.id %}" title="حذف"><i class="far fa-trash"></i></a>
						</th>
					</tr>
				{% endfor %}
			</table>
		
		{% else %}
		<div class="col-md-9 col-sm-9 ">
			<h4>گرایشی در این گروه ثبت نشده است</h4>
			<button type="button" class="btn btn-primary">
				<a href="{% url 'staff:add_orientation' %}" style="color: aliceblue; text-decoration-style: none;">ایجاد گرایش</a>
			</button>
		</div>
		{% endif %}
			
	
	</div>



    
        
{% endblock content %}
    

masters/frontend/templates/staff/system/setGroupAdmin.html
{% extends '../template.html' %}


    
{% block panel_title %}
 تعیین مدیر گروه {{ group.title }} 
{% endblock panel_title %}
    


{% block content %}
<form method="post" class="form-horizontal form-label-left input_mask">
    {% csrf_token %}

    <div class="form-group">
        <label class="control-label col-md-3 col-sm-3 col-xs-12">تعیین مدیر {{ group.title }}</label>
        {% if not pfs %}
            <div class="col-md-9 col-sm-9 ">
                <button type="button" class="btn btn-primary">
                    <a href="{% url 'staff:add_professor' %}" style="color: aliceblue; text-decoration-style: none;">ایجاد حساب استاد</a>
                </button>
                <p>استادی گروه {{ group.title }} ثبت نشده است.</p>
            </div>
        {% else %}
        <div class="col-md-6 col-sm-6 col-xs-12">
            <select name="professor" id="id_professor">
                    {% for pf in pfs %}
                        <option value="{{ pf.professor.id }}">دکتر {{ pf.professor.first_name }} {{ pf.professor.last_name }}</option>
                    {% endfor %}
                </select>
            </div>
        {% endif %}
            <br><br><br>

        <div class="ln_solid"></div>
        <div class="form-group">
            <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                <button type="submit" class="btn btn-success">ثبت</button>
            </div>
        </div>
    </div>
</form>

{% endblock content %}
    