masters/masters/urls.py
from django.contrib import admin
from django.urls import path, include
from masters import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
    path('student/', include('student.urls')),
    path('professor/', include('professor.urls')),
    path('staff/', include('staff.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

masters/staff/urls.py
from django.urls import path
from staff import views, professorView, studentView

app_name = 'staff'

urlpatterns = [
    # PROFESSOR CRUD
    path('add/professor/', professorView.addProfessor, name='add_professor'),
    path('professors/', professorView.addProfessor, name='professor_list'),
    path('professor/<int:id>/edit/', professorView.professorEdit, name='professor_edit'),
    
    # STUDENT CRUD
    path('student/<int:id>/edit/', studentView.studentEdit, name='student_edit'),
    path('add/student/', studentView.addStudent, name='add_student'),
    path('students/', studentView.addStudent, name='student_list'),
    
    # SYSTEM CRUD
    path('add/group/', views.addGroup, name='add_group'),
    path('group/admin/<int:id>', views.setGroupAdmin, name='set_group_admin'),
    path('add/orientation/', views.addOrientation, name='add_orientation'),
    path('group/<int:id>/edit/', views.editGroup, name='edit_group'),
    path('group/<int:id>/delete/', views.error, name='delete_group'),
    path('orientation/<int:id>/edit/', views.editOrientation, name='edit_orientation'),
    path('orientation/<int:id>/delete/', views.deleteOrientation, name='delete_orientation'),
    
    # GET
    path('groups/', views.groups, name='groups'),
    path('group/<int:id>/orientations/', views.groupOrientationList, name='group_orientation_list'),
    path('group/<int:id>/professors/', views.groups, name='group_professor_list'),
    path('group/<int:id>/students/', views.groups, name='group_student_list'),
    path('orientation/<int:id>/students/', views.groups, name='orientation_student_list'),
    path('error/', views.error, name='error'),
    path('<str:username>/', views.dashboard, name='dashboard'),
]

masters/student/urls.py
from django.urls import path
from student import views

app_name = 'student'

urlpatterns = [
    path('jury/', views.juryRequest, name='jury_request'),
    path('disserta/', views.disserta, name='disserta'),
    path('create/dissertation/', views.dissertationCreate, name='create_dissertation'),
    path('report/dissertation/', views.dissertationReport, name='dissertation_report'),
    path('report/dissertation/edit/', views.dissertationReportEdit, name='dissertation_report_edit'),
    path('report/achievement/', views.achievementReport, name='achievement_report'),    
    path('report/achievement/edit/', views.achievementReportEdit, name='achievement_report_edit'), 
    path('<str:username>/', views.dashboard, name='dashboard'),
]

masters/staff/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager
from system.models import User, College

class Staff(User):
    class Meta:
        proxy = True

    class StaffManager(BaseUserManager):
        def get_queryset(self, *args, **kwargs):
            return super().get_queryset(*args, **kwargs).filter(item_type=User.Types.STAFF)

    def save(self, *args, **kwargs):
        self.item_type = User.Types.STAFF
        self.is_staff  = True
        return super().save(*args, **kwargs)

    objects = StaffManager()

    @property
    def fields(self):
        return self.stafffields

class StaffFields(models.Model):
    college = models.ForeignKey(College, on_delete=models.DO_NOTHING)
    staff   = models.OneToOneField(Staff, on_delete=models.CASCADE)

masters/student/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager
from system.models import User, Group, Orientation
from django_jalali.db import models as jmodels

class Student(User):
    class Meta:
        proxy = True

    class StudentManager(BaseUserManager):
        def get_queryset(self, *args, **kwargs):
            return super().get_queryset(*args, **kwargs).filter(item_type=User.Types.STUDENT)

    def save(self, *args, **kwargs):
        self.item_type = User.Types.STUDENT
        return super().save(*args, **kwargs)

    objects = StudentManager()

    @property
    def fields(self):
        return self.studentfields

class StudentFields(models.Model):
    student      = models.OneToOneField(Student, on_delete=models.CASCADE)
    entry_at     = models.DateField(auto_now_add=True)
    is_graduated = models.BooleanField(default=False)
    is_daily     = models.BooleanField(default=True)
    describtion  = models.CharField(max_length=300, blank=True)
    has_disserta = models.BooleanField(default=False)

    # RELATIONS
    group        = models.ForeignKey(Group, on_delete=models.DO_NOTHING)
    orientation  = models.ForeignKey(Orientation, on_delete=models.DO_NOTHING)



class Dissertation(models.Model):
    title       = models.CharField(max_length=500)
    description = models.TextField()
    is_approved = models.BooleanField(default=False)
    created_at  = jmodels.jDateTimeField(auto_now_add=True)
    jury_date   = jmodels.jDateField(blank=True)
    objects     = jmodels.jManager() 
    docfile     = models.FileField(blank=True, upload_to='disserta')

    # RELATIONS
    student     = models.OneToOneField(Student, on_delete=models.CASCADE)



class AchievementReport(models.Model):
    class Status(models.IntegerChoices):
       REJECTED    = 0 
       ACCEPTED    = 1
       IN_PROGRESS = 2

    grade_average    = models.JSONField()
    status           = models.IntegerField(choices=Status.choices, default=Status.IN_PROGRESS)
    report_id        = models.CharField(max_length=20, blank=True)
    created_at       = models.DateField(auto_now_add=True)
    supervisor_ok    = models.BooleanField(default=False)
    manager_ok       = models.BooleanField(default=False)
    supervisor_quote = models.CharField(max_length=400, blank=True)
    manager_quote    = models.CharField(max_length=400, blank=True)
    objects          = models.Manager() 
    
    # RELATIONS
    student          = models.ForeignKey(Student, on_delete=models.CASCADE)
    disserta         = models.ForeignKey(to='DissertationReport', on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['student', 'disserta'], name='report')
        ]

class DissertationReport(models.Model):
    title            = models.CharField(max_length=400, blank=False)
    summary          = models.CharField(max_length=500)
    problems         = models.CharField(max_length=500)
    proceedings      = models.CharField(max_length=500)
    created_at       = models.DateField(auto_now_add=True)
    supervisor_ok    = models.BooleanField(default=False)
    manager_ok       = models.BooleanField(default=False)
    supervisor_quote = models.CharField(max_length=400, blank=True)
    manager_quote    = models.CharField(max_length=400, blank=True)
    objects          = models.Manager() 

    # RELATIONS
    disserta         = models.ForeignKey(Dissertation, on_delete=models.CASCADE)




class JuryRequest(models.Model):
    class Status(models.IntegerChoices):
       REJECTED    = 0 
       ACCEPTED    = 1
       IN_PROGRESS = 2
    status           = models.IntegerField(choices=Status.choices, default=Status.IN_PROGRESS)
    jury_date        = models.DateField()
    created_at       = models.DateField(auto_now_add=True)
    supervisor_ok    = models.BooleanField(default=False)
    supervisor_quote = models.CharField(max_length=400, blank=True)
    manager_ok       = models.BooleanField(default=False)
    manager_quote    = models.CharField(max_length=400, blank=True)
    staff_ok         = models.BooleanField(default=False)   
    staff_quote      = models.CharField(max_length=400, blank=True)
    objects          = models.Manager()
    
    # RELATIONS
    dissertation     = models.OneToOneField(Dissertation, on_delete=models.CASCADE)
    student          = models.OneToOneField(Student, on_delete=models.CASCADE)

masters/system/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from phonenumber_field.modelfields import PhoneNumberField 

class College(models.Model):
    title   = models.CharField(max_length=100, unique=True)
    objects = models.Manager() 


class Group(models.Model):
    title     = models.CharField(max_length=100, unique=True)
    has_admin = models.BooleanField(default=False)
    objects   = models.Manager() 

    # RELATIONS
    college   = models.ForeignKey(College, on_delete=models.CASCADE)

    @property
    def adminstrator(self):
        return self.adminstrator

class Adminstrator(models.Model):
    professor = models.ForeignKey(to='professor.Professor', on_delete=models.DO_NOTHING)
    group     = models.OneToOneField(Group, primary_key=True, on_delete=models.CASCADE)


class Orientation(models.Model):
    title   = models.CharField(max_length=100, unique=True)
    objects = models.Manager() 
    
    # RELATIONS
    group   = models.ForeignKey(Group, on_delete=models.CASCADE)

class User(AbstractUser):
    
    class Gender(models.IntegerChoices):
        FEMALE = 0
        MALE   = 1
        NONE   = 2
    
    class Types(models.IntegerChoices):
        STUDENT   = 0
        PROFESSOR = 1
        STAFF     = 2
        OTHER     = 3

    first_name = models.CharField(max_length=30, blank=False)
    last_name  = models.CharField(max_length=30, blank=False)
    password   = models.CharField(max_length=100, blank=False)
    email      = models.EmailField(unique=False)
    username   = models.CharField(unique=True, max_length=10)
    n_code     = models.CharField(unique=True, max_length=10)
    phone      = PhoneNumberField(blank=False)
    item_type  = models.IntegerField(choices=Types.choices, default=Types.OTHER)
    is_staff   = models.BooleanField(default=False)
    gender     = models.IntegerField(choices=Gender.choices, default=Gender.NONE)
    created_at = models.DateField(auto_now_add=True, blank=True)
    is_active  = models.BooleanField(default=True)

    REQUIRED_FIELDS = ['n_code']

    def save(self, *args, **kwargs):
        print(self.password)
        if not self.is_superuser:
            if not self.password:
                print("password is None")
                self.set_password(self.n_code)
            else:
                print("password is not None")
                self.set_password(self.password)
        print(self.password)
            
        return super().save(*args, **kwargs)



class JuryInvitation(models.Model):
    class Status(models.IntegerChoices):
       REJECTED    = 0 
       ACCEPTED    = 1
       IN_PROGRESS = 2
    status     = models.IntegerField(choices=Status.choices, default=Status.IN_PROGRESS)
    created_at = models.DateField(auto_now_add=True)
    jury_date  = models.DateField()
    objects    = models.Manager()
    
    # RELATIONS
    professor  = models.ForeignKey(to="professor.Professor", on_delete=models.DO_NOTHING)
    disserta   = models.ForeignKey(to='student.Dissertation', on_delete=models.DO_NOTHING)


class Supervisor(models.Model):
    class Percent(models.IntegerChoices):
        Q1   = 25
        HALF = 50
        Q3   = 75
        FULL = 100
    student   = models.ForeignKey(to="student.Student", on_delete=models.DO_NOTHING, related_name="student")
    professor = models.ForeignKey(to="professor.Professor", on_delete=models.DO_NOTHING, related_name="professor")
    percent   = models.IntegerField(choices=Percent.choices, default=Percent.FULL)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['student', 'professor'], name="supervisor")
        ]
  

masters/student/forms.py
from django import forms
from professor.models import Professor, ProfessorFields
from phonenumber_field.formfields import PhoneNumberField
from system.models import Group, Orientation, User
from student.models import Dissertation, DissertationReport, AchievementReport
from django.core.exceptions import ValidationError
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget


# from ckeditor.fields import RichTextFormField

class DissertationForm(forms.ModelForm):
    class Meta:
        model  = Dissertation
        fields = ['title', 'description', 'docfile']

    # def __init__(self, *args, **kwargs):
    #     super(DissertationForm, self).__init__(*args, **kwargs)
    #     self.fields['jury_date'] = JalaliDateField(# date format is  "yyyy-mm-dd"
    #         widget=AdminJalaliDateWidget # optional, to use default datepicker
    #     )

        # you can added a "class" to this field for use your datepicker!
        # self.fields['date'].widget.attrs.update({'class': 'jalali_date-date'})


class DRForm(forms.ModelForm):
    class Meta:
        model  = DissertationReport
        fields = ['title', 'summary', 'problems', 'proceedings',]

masters/student/views.py
from django.shortcuts import render, redirect
from jalali_date import datetime2jalali, date2jalali
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
import jdatetime

from student.forms import DissertationForm, DRForm
from student.models import Dissertation
from system.models import User



# Create your views here.
def juryRequest(request):
    if request.user.item_type != User.Types.STUDENT:
        return redirect('system:logout')
    else:
        pass

    return render(request, 'student/juryRequest.html', {})
def achievementReport(request):
    if request.user.item_type != User.Types.STUDENT:
        return redirect('system:logout')
    else:
        pass

    return render(request, 'student/achievementReport.html', {})

def achievementReportEdit(request):
    if request.user.item_type != User.Types.STUDENT:
        return redirect('system:logout')
    else:
        pass

    return render(request, 'student/achievementReportEdit.html', {})

def dissertationReportEdit(request):
    if request.user.item_type != User.Types.STUDENT:
        return redirect('system:logout')
    else:
        pass

    return render(request, 'student/dissertationReportEdit.html', {})

@login_required
def dashboard(request, username):
    if request.user.item_type != User.Types.STUDENT:
        return redirect('system:logout')
    else:
        pass
    return render(request, 'student/dashboard.html', {})

@login_required
def disserta(request):
    try:
        dissertation = Dissertation.objects.get(student=request.user)
    except ObjectDoesNotExist:
        return redirect('student:dashboard', username=request.user.username)
    return render(request, 'student/disserta.html', {'disserta':dissertation})


@login_required
def dissertationCreate(request):
    # jalali_join = datetime2jalali(request.user.date_joined).strftime('%y/%m/%d _ %H:%M:%S')
    if request.user.item_type != User.Types.STUDENT:
        return redirect('system:logout')
    else:
        pass
    if request.user.studentfields.has_disserta:
        return redirect('student:dashboard')
    else:
        pass
    if request.method == "POST":
        form = DissertationForm(request.POST, request.FILES)
        print("method")
        if form.is_valid():
            print("form is valid")
            instance                  = form.save(commit=False)
            instance.student          = request.user
            request.user.studentfields.update(has_disserta=True)
            instance.save()
            messages.warning(request, 'شما می توانید پایاننامه خود را ویرایش کنید')
            return redirect('student:dashboard', username=request.user.username)
    else:
        form = DissertationForm()
    context = {
        'form': form
    }
    return render(request, 'student/dissertationCreate.html', context=context)


@login_required
def dissertationReport(request):
    # jalali_join = datetime2jalali(request.user.date_joined).strftime('%y/%m/%d _ %H:%M:%S')
    if request.user.item_type != User.Types.STUDENT:
        return redirect('system:logout')
    else:
        pass

    try:
        Dissertation.objects.get(student=request.user)
        return redirect('student:disserta')
    except ObjectDoesNotExist:
        pass
    if request.method == "POST":
        form = DRForm(request.POST)
        if form.is_valid():
            instance         = form.save(commit=False)
            instance.student = request.user
            # instance.jury_date = jdatetime.date(int(jdate[0]), int(jdate[1]), int(jdate[2]))
            instance.save()
            return redirect('student:dashboard', username=request.user.username)
            # jalali_join = date2jalali(the_date).strftime('%y/%m/%d')
    else:
        form = DissertationForm()
    context = {
        'form': form
    }
    return render(request, 'student/dissertationCreate.html', context=context)

masters/frontend/templates/staff/student/addStudent.html
{% extends '../template.html' %}



{% block page_title %}
    ایجاد حساب دانشجویان
{% endblock page_title %}
    

{% block content %}

            <div class="x_content">
                <br/>
                <form method="POST" class="form-horizontal form-label-left input_mask">
                    {% csrf_token %}
                    <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                        <input type="text" class="form-control has-feedback-left" id="id_first_name" name="first_name" placeholder="نام">
                        {{ form.first_name.errors }}
                        <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                    </div>

                    <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                        <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="نام خانوادگی">
                        <span class="fa fa-user form-control-feedback left" aria-hidden="true"></span>
                        {{ form.last_name.errors }}
                    </div>

                    <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                        <input type="text" class="form-control has-feedback-left" id="id_email" name="email" placeholder="ایمیل">
                        <span class="fa fa-envelope form-control-feedback left" aria-hidden="true"></span>
                        {{ form.email.errors }}
                    </div>

                    <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                        <input type="text" class="form-control" id="id_phone" name="phone" pattern="+98-[0-9]{3}-[0-9]{7}" placeholder="تلفن">
                        <span class="fa fa-phone form-control-feedback left" aria-hidden="true"></span>
                        {{ form.phone.errors }}
                    </div>

                    <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                        <input type="text" class="form-control" id="id_n_code" name="n_code" placeholder="کد ملی">
                        <span class="fa fa-id-card form-control-feedback left" aria-hidden="true"></span>
                        {{ form.n_code.errors }}
                    </div>

                    <div class="col-md-6 col-sm-6 col-xs-12 form-group has-feedback">
                        <input type="text" class="form-control" id="id_username" name="username" placeholder="شماره دانشجویی">
                        <span class="fa fa-id-card form-control-feedback left" aria-hidden="true"></span>
                        {{ form.username.errors }}
                    </div>


                    <label for="message">توضیحات شرایط خاص:( حداکثر ۳۰۰ کاراکتر)</label>
                    <textarea id="id_description" class="form-control" name="description"
                              data-parsley-trigger="keyup"
                              data-parsley-maxlength="300"
                              data-parsley-validation-threshold="10"></textarea>


                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">دانشجوی روزانه؟</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input type="checkbox" name="is_daily" id="id_is_daily">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">گرایش</label>
                        
                        {% if not orientations %}
                            <div class="col-md-9 col-sm-9 ">
                                <p>ابتدا باید گرایش ایجاد کنید</p>
                                <button type="button" class="btn btn-primary">
                                    <a href="{% url 'staff:add_orientation' %}" style="color: aliceblue; text-decoration-style: none;">ایجاد گرایش</a>
                                </button>
                            </div>
                        {% else %}
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <select name="group" id="id_group">
                                    {% for orientation in orientations %}
                                        <option value="{{ orientation.id }}">{{ orientation.title }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endif %}
                            
                    </div>



                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">جنسیت</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select name="gender" id="id_gender">
                                <option value="0">مونث</option>
                                <option value="1">مذکر</option>
                                <option value="2">سایر</option>
                            </select>
                        </div>
                        {{ form.gender.errors }}
                    </div>


                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
                            <!-- <button type="submit" class="btn btn-primary">انصراف</button> -->
                            <button type="submit" class="btn btn-success">ارسال</button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock content %}